export const DataCelebrations = [
    {
        id:1,
        title:"Staff Enhancement Program",
        date:"03.06.2024",
        image:"/Images/Tamil/Celebrations/StaffEnhancement.jpg",
    },
    {
        id:2,
        title:"Inauguration Day of 2024",
        date:"14.06.2024",
        image:"/Images/Tamil/Celebrations/Inaguration.jpg",
    },
    {
        id:3,
        title:"Table Week",
        date:"18.06.2024",
        image:"/Images/Tamil/Celebrations/Table Competition.jpg",
    },
    {
        id:4,
        title:"Reading Week",
        date:"24.06.2024",
        image:"/Images/Tamil/Celebrations/Reading Competition.jpg",
    },
    {
        id:5,
        title:"Calligraphy Practice Week",
        date:"01.07.2024",
        image:"/Images/Tamil/Celebrations/Caligraphy.jpg",
    },
    {
        id:6,
        title:"Inaguration of Teams and Clubs",
        date:"05.07.2024",
        image:"/Images/Tamil/Celebrations/House-Activities.jpg",
    },
    {
        
        id:6,
        title:"Orientation on Emergency Medical Care",
        date:"11.07.2024",
        image:"/Images/Tamil/Celebrations/Medical Awarness.jpg",
    },
    {
        id:6,
        title:"Kamaraj Education Development Day",
        date:"15.07.2024",
        image:"/Images/Tamil/Celebrations/Kamaraj.jpg",
    },
    {
        id:7,
        title:"New Classroom Opening",
        date:"18.07.2024",
        image:"/Images/Tamil/Celebrations/NewClass.jpg",
    },
    {
        id:8,
        title:"Sports Day",
        date:"10.08.2024",
        image:"/Images/Tamil/Celebrations/Sports Day.jpg",
    },
    {
        id:9,
        title:"Independence Day",
        date:"15.08.2024",
        image:"/Images/Tamil/Celebrations/Independence.jpg",
    },
    {
        id:9,
        title:"PTA Meeting ",
        date:"21.08.2024",
        image:"/Images/Tamil/Celebrations/ThinkingProgram.jpg",
    },
    {
        id:10,
        title:"Singing Competition",
        date:"30.08.2024",
        image:"/Images/Tamil/Celebrations/Singing-Competition.jpg",
    },
    {
        id:11,
        title:"Mathematics Exhibition",
        date:"02.09.2024",
        image:"/Images/Tamil/Celebrations/Maths-Exhibition.jpg",
    },
    {
        id:12,
        title:"Teacher's Day",
        date:"05.09.2024",
        image:"/Images/Tamil/Celebrations/Teacher's Day.jpg",
    },
    {
        id:13,
        title:"Dance Competition",
        date:"18.10.2024",
        image:"/Images/Tamil/Celebrations/Dance-Competition.jpg",
    },
    {
        id:18,
        title:"Educational Excursion",
        date:"26.10.2024",
        image:"/Images/Tamil/Celebrations/Tour.jpg",
    }, 
    {
        id:14,
        title:"Science Exhibition",
        date:"29.10.2024",
        image:"/Images/Tamil/Celebrations/Science-Exhibition.jpg",
    },
    {
        id:15,
        title:"Diwali Celebration",
        date:"29.10.2024",
        image:"/Images/Tamil/Celebrations/Deepavali.jpg",
    },
    {
        id:19,
        title:"Fancy Dress Competition",
        date:"13.11.2024",
        image:"/Images/Tamil/Celebrations/Fancy.jpg",
    },
    {
        id:16,
        title:"Children's Day",
        date:"14.11.2024",
        image:"/Images/Tamil/Celebrations/Children's Day.jpg",
    },
    {
        id:16,
        title:"Clay Modeling",
        date:"29.11.2024",
        image:"/Images/Tamil/Celebrations/Clay-Modeling.jpg",
    },
   
    {
        id:17,
        title:"Christmas Day",
        date:"23.12.2024",
        image:"/Images/Tamil/Celebrations/Christmas day.jpg",
    },
];
